FROM apache/airflow:2.8.3-python3.11

USER root

# Install any system dependencies you want (vim is just an example)
RUN apt-get update \
  && apt-get install -y --no-install-recommends \
         vim \
  && apt-get autoremove -yqq --purge \
  && apt-get clean \
  && rm -rf /var/lib/apt/lists/*

  
USER airflow
  
# Install Python dependencies for your ML pipeline
COPY requirements.txt /requirements.txt
RUN pip install --no-cache-dir -r /requirements.txt
