# Dockerfile
FROM apache/airflow:3.0.2 

USER root
RUN apt-get update && apt-get install -y gcc g++ libpq-dev

# Add the symlink   
RUN ln -s /opt/airflow/dags/repo/configs /opt/airflow/configs

USER airflow
COPY requirements.txt /
RUN pip install --no-cache-dir -r /requirements.txt
