mlflow:
  tracking_uri: http://mlflow-server:5000
  experiment_name: iris-classification

s3:
  bucket: ml-artifact-bucket-1
  model_path: models/
  data_path: data/iris.csv

# Hyperparameter configuration for A/B testing
hyperparameters:
  base:
    n_estimators: 100
    max_depth: 5
    max_features: sqrt
    min_samples_split: 2
    min_samples_leaf: 1
    random_state: 42
    test_size: 0.2
  
  variants:
    - name: "deep_forest"
      description: "Deeper trees with more estimators"
      n_estimators: 200
      max_depth: 10
      max_features: sqrt
      min_samples_split: 5
      min_samples_leaf: 2
      random_state: 42
      test_size: 0.2
    
    - name: "shallow_wide"
      description: "Shallow trees with many estimators"
      n_estimators: 300
      max_depth: 3
      max_features: log2
      min_samples_split: 10
      min_samples_leaf: 5
      random_state: 42
      test_size: 0.2
    
    - name: "conservative"
      description: "Conservative parameters for stability"
      n_estimators: 50
      max_depth: 4
      max_features: sqrt
      min_samples_split: 8
      min_samples_leaf: 4
      random_state: 42
      test_size: 0.2
